import numpy as np
import matplotlib.pyplot as plt


def uniform_mesh_quad4(lx, ly, ux, uy, nx, ny):
    '''Create a uniform mesh of a rectangular domain

    Parameters:
        lx, ly: co-ordinates of the lower left corner of the domain
        ux, uy: co-ordinates of the upper right corner of the domain
        nx, ny: number of elements in the x and y axis respectively    
    '''
    xx = np.linspace(lx, ux, nx+1)
    yy = np.linspace(ly, uy, ny+1)
    x, y = np.meshgrid(xx, yy)
    return (x, y)

def plot_mesh_quad4(x, y):
    '''Create plot a generated mesh
    
    Parameters:
        x, y: The mesh arrays generated by uniform_mesh_quad4
    '''
    plt.plot(x, y, 'b--o', np.transpose(x), np.transpose(y), 'b--')
    plt.show()


if __name__ == '__main__' :
    x, y = uniform_mesh_quad4(0,0,5,6,5,3)
    plot_mesh_quad4(x, y)